language: php

php:
  #- 5.5
  #- 5.6
  - 7.0
  #- 7.1

matrix:
  fast_finish: true

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e 'CREATE DATABASE typo3;'
  - composer self-update

install:
  - composer install

before_script:
  - export TYPO3_PATH_WEB=$PWD/.build/web
  - mkdir -p .build/web/typo3conf
  - .build/bin/typo3cms install:setup --non-interactive --database-host-name=127.0.0.1 --database-port=3306 --database-user-name=travis --database-name=typo3 --use-existing-database --admin-user-name=travis --admin-password=travis123456! --site-setup-type=site
  - .build/bin/typo3cms install:generatepackagestates
  - .build/bin/typo3cms database:updateschema *.add,*.change
  - .build/bin/typo3cms cache:flushgroups system
  - .build/bin/typo3cms configuration:set --path SYS/trustedHostsPattern --value ".*"

  - echo "Run php in-built server - background process"
  - nohup bash -c "php -S localhost:8000 2>&1 -t .build/web/ &" && sleep 1; cat nohup.out

script:
  - >
    echo "Running PHP PSR-2 coding standard checks";
    .build/bin/phpcs --standard=PSR2 src/ tests/;

  - >
    echo;
    curl -vsf 'http://127.0.0.1:8000/typo3/index.php' &> /dev/stdout

notifications:
  email: false
