sudo: required
dist: trusty
language: php
php:
  #- 5.5
  #- 5.6
  - 7.0
  #- 7.1
services:
  - mysql

env:
  - COMPOSER_FLAGS="--prefer-dist --optimize-autoloader" TYPO3_VERSION="^7.6"

matrix:
  fast_finish: true

addons:
  hosts:
    - typo3-whoops.local

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e 'CREATE DATABASE typo3;'
  - composer self-update

install:
  - travis_retry composer install $COMPOSER_FLAGS --no-interaction

before_script:
  - export TYPO3_PATH_WEB=$PWD/.build/web
  - mkdir -p .build/web/typo3conf
  - .build/bin/typo3cms install:setup --non-interactive --database-host-name=127.0.0.1 --database-port=3306 --database-user-name=travis --database-name=typo3 --use-existing-database --admin-user-name=travis --admin-password=travis123456! --site-setup-type=site
  - .build/bin/typo3cms install:generatepackagestates
  - .build/bin/typo3cms database:updateschema *.add,*.change
  - .build/bin/typo3cms extension:activate whoops
  - .build/bin/typo3cms cache:flushgroups system
  - .build/bin/typo3cms configuration:set --path SYS/trustedHostsPattern --value ".*"

script:
  - >
    echo "Running PHP PSR-2 coding standard checks";
    .build/bin/phpcs --standard=PSR2 src/ tests/;

  - >
    echo "Checking TYPO3 frontend output";
    curl -s localhost | grep "Whoops! There was an error."

notifications:
  email: false
