sudo: required
dist: trusty
language: php
php:
  #- 5.5
  #- 5.6
  - 7.0
  #- 7.1
services:
  - mysql

env:
  - COMPOSER_FLAGS="--prefer-dist --optimize-autoloader" TYPO3_VERSION="^7.6"

matrix:
  fast_finish: true

addons:
  hosts:
    - typo3-whoops.local

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # setup mysql
  - mysql -e 'CREATE DATABASE typo3_whoops_test;'
  - mysql -u travis -D typo3_whoops_test < .travis/mysql/typo3_whoops_test.sql
  # setup apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # setup php-fpm
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp .travis/php/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # setup virtual host
  - sudo cp -f .travis/apache/typo3-whoops.local.conf /etc/apache2/sites-available/typo3-whoops.local.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/typo3-whoops.local.conf
  - sudo a2dissite 000-default.conf
  - sudo a2ensite typo3-whoops.local.conf
  - sudo service apache2 restart

install:
  - travis_retry composer install $COMPOSER_FLAGS --no-interaction

before_script:
  - phpenv config-rm xdebug.ini
  - export TYPO3_PATH_WEB=$PWD/.build/web
  - mkdir -p .build/web/typo3conf
  - cp -f .travis/typo3/AdditionalConfiguration.php .build/web/typo3conf/AdditionalConfiguration.php
  - cp -f .travis/typo3/LocalConfiguration.php .build/web/typo3conf/LocalConfiguration.php

script:
  - >
    echo "Running PHP PSR-2 coding standard checks";
    ./.build/bin/phpcs --standard=PSR2 src/ tests/;

  - >
    echo "Setup TYPO3 via console";
    ./.build/bin/typo3cms install:fixfolderstructure;
    ./.build/bin/typo3cms install:generatepackagestates;

  - >
    echo "Checking TYPO3 frontend output";
    curl -s localhost | grep "Whoops! There was an error."

after_failure:
  - >
    echo "Apache2 vHost configuration:";
    sudo cat /etc/apache2/sites-available/typo3-whoops.local.conf;
  - >
    echo "Apache2 error log:";
    sudo cat $TRAVIS_BUILD_DIR/apache-error.log;
  - >
    echo "cURL from localhost:";
    curl localhost;
  - sleep 5
